sonar.projectKey=labmcp
sonar.projectName=labmcp
sonar.python.version=3.14

sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=testresults.xml

sonar.exclusions=.gitea/**,.venv/**,README.md
